### ISSUE TITLE
this tool don't work at FireFox 39.0

### ISSUE THREAD

**Issue by ghost** [silverwind/uppie#1]
hi,
thank you for your share.
I download that demo and have a try. it can work at chrome but not FireFox 39.0.
I use it in wrong way?

**Comment by silverwind** [comment]
As mentioned in the readme, this will only work in a recent Firefox Nightly (42+), the API is brand new. I plan on doing a 1.0 release once Firefox 42 is released, in around 2 months.

**Comment by ghost** [comment]
Thank you, 
What make me confuse is that  the lastest version of FF is 39  and how you know it will work at FF 42, until I find a website:https://bugzilla.mozilla.org/show_bug.cgi?id=1164310 , and see it will be fixed at 42+:

Tracking Flags: 
status-firefox40:   affected
status-firefox41:   affected
status-firefox42:   fixed

And see you in this one :https://bugzilla.mozilla.org/show_bug.cgi?id=846931

You are so cool!
