### ISSUE TITLE
ASP.NET Core cannot cast `files[]` name

### ISSUE THREAD

**Issue by Creta5164** [silverwind/uppie#10]
ASP.NET Core cannot detect like `files[]` name.  
Can uppie make option to remove `[]` brackets from name? (`files[]` to `files`)  
https://github.com/silverwind/uppie/blob/58a4eb61e0d1cfad3e61e1b1658a706407199209/uppie.js#L66-L70
https://github.com/silverwind/uppie/blob/58a4eb61e0d1cfad3e61e1b1658a706407199209/uppie.js#L86-L90
https://github.com/silverwind/uppie/blob/58a4eb61e0d1cfad3e61e1b1658a706407199209/uppie.js#L117-L121
https://github.com/silverwind/uppie/blob/58a4eb61e0d1cfad3e61e1b1658a706407199209/uppie.js#L134-L138

![image](https://user-images.githubusercontent.com/13521406/54878346-a3069f00-4e6e-11e9-8bb7-b8a01b290abd.png)  
![image](https://user-images.githubusercontent.com/13521406/54878354-bf0a4080-4e6e-11e9-8e6a-91639cd15698.png)

**Comment by silverwind** [comment]
Fixed in 1.1.0, you can now specify the name used as an option: 

```js
uppie(node, {name: "files"}, callback);
