### ISSUE TITLE
Upload isn't working!

### ISSUE THREAD

**Issue by iamtorsten** [silverwind/uppie#5]
Does not upload any file to the server?!?

Tryed with chrome Version 52.0.2743.82 m (64-bit)

Whats going wrong?

**Comment by iamtorsten** [comment]
[example.txt](https://github.com/silverwind/uppie/files/381451/example.txt)

**Comment by silverwind** [comment]
Your example looks already, but does your web server handle POST requests to `/upload`? Can you show the code there?

**Comment by iamtorsten** [comment]
Think so. Its an xampp standard installation.

**Comment by silverwind** [comment]
Well, I guess you have to look on the server side to investigate further. Uppie is sending regular `multipart/formdata` uploads. Maybe you need to enable the server to handle multiple files in a single request.

**Comment by silverwind** [comment]
Also, if it's just a plain PHP file that receives the uploads, you should POST to `/upload.php` or similar most likely.

**Comment by iamtorsten** [comment]
Tested with another upload.php. With this i can upload files without directories. So server is config well.

With yours it does simple nothing. 

Whats going wrong?

**Comment by silverwind** [comment]
The only issue I can think of is that your php code may expect a leading slash on the `filename` field, which I'm not sending. Also, if it's a run-of-the-mill PHP library, it's likely going to need modification to handle directories. You'll need to adapt it to handle paths like this:

```
Content-Disposition: form-data; name="file"; filename="docs/1.txt"
Content-Disposition: form-data; name="file"; filename="docs/path/2.txt"
Content-Disposition: form-data; name="file"; filename="docs/path/to/3.txt"
```

**Comment by iamtorsten** [comment]
Ok so it cant be done with it?

**Comment by silverwind** [comment]
Try this branch which includes a leading slash in the filename fields. It's a recent change in the [spec](https://wicg.github.io/directory-upload/proposal.html#h-form-submission) which I've not implemented yet, maybe it helps:

https://github.com/silverwind/uppie/tree/leading-slash

**Comment by iamtorsten** [comment]
Ok ill give it a try tonight and report back!

**Comment by iamtorsten** [comment]
Nope uploads simply nothing. Don’t work!

Von: silverwind [mailto:notifications@github.com] 
Gesendet: Montag, 25. Juli 2016 19:48
An: silverwind/uppie uppie@noreply.github.com
Cc: mrklintscher torsten.klinger@googlemail.com; Author author@noreply.github.com
Betreff: Re: [silverwind/uppie] Upload isn't working! (#5)

Try this branch which includes a leading slash in the filename fields. It's a recent change in the spec https://wicg.github.io/directory-upload/proposal.html#h-form-submission  which I've not implemented yet, maybe it helps:

https://github.com/silverwind/uppie/tree/leading-slash

**Comment by silverwind** [comment]
Post your php script and I'll see what I can do.
