### ISSUE TITLE
Console TypeError: this is undefined

### ISSUE THREAD

**Issue by drnkwati** [silverwind/uppie#7]
Hi
I get this in my console
TypeError: this is undefined
Please can anyone help here I have not been able to figure out why
I think its caused by line 9 in uppie where we have 
this.Uppie = m();
thanks

**Comment by silverwind** [comment]
`this` should refer to `window` in the browser. What environment are you running in?

**Comment by drnkwati** [comment]
I am in browser, why not reference the window object directly?

**Comment by silverwind** [comment]
IIRC, this is because in web workers, there's no `window` global variable, only `self` and in both cases `this` should point to the current global object. Thought it's probably unlikely would run it in a worker.

**Comment by silverwind** [comment]
Maybe the solution is to more closely adapt this [umd wrapper](https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js).

**Comment by silverwind** [comment]
I've updated the module header, can you try if current master (https://raw.githubusercontent.com/silverwind/uppie/master/uppie.min.js) works for you?

**Comment by drnkwati** [comment]
Cool man.
issues resolved it now works ok.

**Comment by silverwind** [comment]
Okay, released as 1.0.7.
