### ISSUE TITLE
Uppie folder upload

### ISSUE THREAD

**Issue by ghost** [silverwind/uppie#9]
Looks exactly like what I am after - thanks for sharing

I can't figure out where do I specify the server folder to upload this into
Hope someone can help me with that

Thanks
Alex

**Comment by silverwind** [comment]
This is only the browser part of a file upload, the server part is up to you to implement. You need a script that accepts a `multipart/form-data` encoded POST request which can decode the `filename` multipart field into a proper path on the server.

The README has a PHP example, but I would not use it as-is, at minimum it needs proper sanitation of `..` path segments. If your server is Node.js, you can for example use [busboy](https://github.com/mscdex/busboy) to decode the data.

**Comment by ghost** [comment]
Thanks for the feedback,
I am new in this and what I see here is much over my head
I was looking for a simple all-in-one solution

Thanks again
